export const REQUEST_NAME = {
    VIEW_MENU: 'VIEW MENU',
    MORE_WATER: 'MORE WATER',
    NEED_SOMETHING: 'NEED SOMETHING?',
    REQUEST_BILL: 'REQUEST BILL',
    SEND_MESSAGE: 'CUSTOM FEATURE',
    DO_NOT_DISTURB: 'DO NOT DISTURB'
}

export const REQUEST_TYPE = {
    MENU: 'MENU',
    WATER: 'WATER',
    HELP: 'HELP',
    BILL: 'BILL',
    CHAT: 'CHAT',
    DND: 'DND'
}

